services:
  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
  wordpress:
    container_name: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    expose:
      - "9000"
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
  mariadb:
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    expose:
      - "3306"
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/gangouil/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/gangouil/data/mariadb'
      
networks:
  inception:
    driver: bridge
